### ISSUE TITLE
Failed to activate the language-robot-framework package

### ISSUE THREAD

**Issue by AlinaGab** [wingyplus/language-robot-framework#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [language-robot-framework](https://github.com/wingyplus/language-robot-framework) package, v0.6.0
### Stack Trace

Failed to activate the language-robot-framework package

```
At Cannot read property 'scopeName' of undefined

TypeError: Cannot read property 'scopeName' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:139:30)
    at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1091:35)
    at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2412:33)
    at /Users/agabaraeva/.atom/packages/language-robot-framework/index.coffee:15:23
    at Array.forEach (native)
    at Object.module.exports.activate (/Users/agabaraeva/.atom/packages/language-robot-framework/index.coffee:14:10)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
```
### Commands

```
     -1:36.6 encoding-selector:show (atom-text-editor.editor)
     -1:31.6 grammar-selector:show (atom-text-editor.editor)
     -1:25.7 core:move-down (atom-text-editor.editor.mini)
     -1:25.5 core:confirm (atom-text-editor.editor.mini)
     -1:18.8 script:run (atom-text-editor.editor)
     -0:28.2 grammar-selector:show (atom-text-editor.editor)
     -0:23.5 core:move-down (atom-text-editor.editor.mini)
     -0:14.7 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-atom-light-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-atom-api, v0.7.0
language-gherkin, v1.0.1
language-robot-framework, v0.6.0
minimap, v4.7.5
script, v2.18.0

# Dev
No dev packages
```

**Comment by wingyplus** [comment]
Steps to reproduce:
1. Disable package.
2. Reopen atom.
3. Enable package.

**Comment by wingyplus** [comment]
@AlinaGab thank you for reported the bug. It fixed in version 0.7.0 now

**Comment by ariel-cossio** [comment]
Hi @wingyplus, I am seeing this error after update to Atom 1.2.0.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [language-robot-framework](https://github.com/wingyplus/language-robot-framework) package, v0.9.0

### Stack Trace

Failed to activate the language-robot-framework package

```
At Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:160:22)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at Object.module.exports.activate (/Users/ariel/.atom/packages/language-robot-framework/lib/robot.coffee:25:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at Object.module.exports.activate (/Users/ariel/.atom/packages/language-robot-framework/lib/robot.coffee:25:19)
```

### Commands

```
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by wingyplus** [comment]
Maybe I will reopen issue and reproduce again.

**Comment by marwek** [comment]
Hi, maybe this will be useful.
1. Open editor with project 
2. python project for developing custom keywords for robotframework 

Atom opened with theme: seti-ui and monokai-seti

**Atom Version**: 1.2.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [language-robot-framework](https://github.com/wingyplus/language-robot-framework) package, v0.9.0

### Stack Trace

Failed to activate the language-robot-framework package

```
At Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at Package.module.exports.Package.activate (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package-manager.js:512:21)
    at Object.module.exports.activate (C:\Users\XXXXXX\.atom\packages\language-robot-framework\lib\robot.coffee:46:28)
    at Package.module.exports.Package.activateNow (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:170:19)
    at C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package-manager.js:512:21)
    at Object.module.exports.activate (C:\Users\XXXXXX\.atom\packages\language-robot-framework\lib\robot.coffee:46:28)
    at Package.module.exports.Package.activateNow (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:170:19)
    at C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\XXXXXX\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package-manager.js:512:21)
```

### Commands

```
  3x -0:15.7.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "language-ruby",
      "language-php",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-toml",
      "metrics",
      "welcome",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-make",
      "background-tips",
      "language-yaml",
      "about"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.4
atom-material-ui, v0.8.0
autocomplete-python, v0.10.3
json-colorer, v0.3.0
json-schema, v0.1.15
keyboard-localization, v1.4.10
language-arduino, v0.3.1
language-gherkin-i18n, v1.2.0
language-powershell, v2.1.0
language-svg, v0.9.0
language-vbscript, v0.6.1
linter, v1.11.1
linter-flake8, v1.9.2
linter-jsonlint, v1.0.1
pretty-json, v0.4.1
python-tools, v0.6.6
robot-selenium-snippet, v1.0.1
run-in-terminal, v0.5.0
svg-preview, v0.6.1
visualstudio-terminals, v0.7.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by wingyplus** [comment]
@marwek Thanks for your information.
